### ISSUE TITLE
¿como se puede llamar a las velas?

### ISSUE THREAD

**Issue by fcatalan** [orionx-dev/orionx-sdk-js#25]
¿Como es el nombre del servicio que entrega las velas para un determinado tiempo y en tiempo real?.

**Comment by cristobalpina** [comment]
Hola fcatalan,

Actualmente no está incorporado en el SDK el método que entrega la información de las velas que mencionas. 
El método está en la [API de Orionx](https://orionx.com/developers/test), puedes guiarte por este ejemplo.

```graphql
{
  marketStats(marketCode: "CHACLP", aggregation: d1) {
    _id
    open
    close
    high
    low
    variation
    average
    volume
    volumeSecondary
    count
    fromDate
    toDate
  }
}
```
Puedes dejar un PR si necesitas el método en el SDK o esperar a que lo agregemos nosotros. Voy a intentar de que sea lo antes posible.

Saludos
