### ISSUE TITLE
 core-js@2.6.12: core-js@<3.4 is no longer maintained

### ISSUE THREAD

**Issue by lathanbritz** [orionx-dev/orionx-sdk-js#28]
warning orionx-sdk > babel-runtime > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

**Comment by iWyse** [comment]
How did you fix it ?

**Comment by joadr** [comment]
It was merged
