### ISSUE TITLE
CORS Heard intermittent response

### ISSUE THREAD

**Issue by lathanbritz** [orionx-dev/orionx-sdk-js#34]
`Access to fetch at 'https://api2.orionx.com/graphql' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Requests intermittently receive the response.

<img width="1590" alt="Screen Shot 2022-04-18 at 19 00 24" src="https://user-images.githubusercontent.com/508629/163890567-0f919a4d-7369-4937-8681-9809572e75a8.png">

**Comment by joadr** [comment]
How often did this happen? It should be resolved by now with the latest versions

**Comment by lathanbritz** [comment]
Will monitor and look for this again, i could not find any repeatable operation to reproduce it. But it would show up pretty easily if you ran many requests, ie fetch balances, then place a few limit orders then cancel all orders.

**Comment by joadr** [comment]
As we have configured cors at an application level, if a request fails at network level, cors headers are not sent. We had a gateway timeout set with a very low value at network level, so I suspect that it could be that the request took a bit longer, and sent 504 error with cors error in console, as we have found out in other cases. We have increased the timeout limit to avoid this.

As we don't have a way to be sure that that is the root of this issue, but we suspect it is as it solved the same issue for other integrations, what do you think if we close the issue for now and you hit us back if it happens again so we can do a more in depth investigation?

**Comment by lathanbritz** [comment]
Sound good to me thanks for the info. Agree the analysis, as this would more frequently happen when multiple requests were getting pushed. So possibly one having a slow response causes the other to time out. I think as max I was pushing x4 cancels and then x2 new limit orders (one after the other). 



And even possibly a fix already in place. Will monitor and if I get it again in a more repeatable manner I will forward you information.
