### ISSUE TITLE
API broken.

### ISSUE THREAD

**Issue by lathanbritz** [orionx-dev/orionx-sdk-js#35]
Looks like changes have been deployed to production.

Is there some kind of call back to validate the API version called against?
<img width="1013" alt="Screen Shot 2022-04-22 at 12 41 25" src="https://user-images.githubusercontent.com/508629/164758183-06494977-0623-4bdb-8877-29989d7269da.png">

**Comment by joadr** [comment]
I'm checking!

**Comment by lathanbritz** [comment]
this is via the call 

const token = await Orionx.requestRealtimeToken()

**Comment by joadr** [comment]
Is it the only one that fails for you?
It's weird because that method is working for me 😕

**Comment by lathanbritz** [comment]
const orderbook =  await Orionx.marketOrderBook({
                        marketCode: 'XRPCLP', 
                        limit:  50
                    })
                    console.log('orderbook', orderbook)

returning same error as well it looks like, maybe its a ip ban then at the CORS policy level?

**Comment by lathanbritz** [comment]
<img width="1303" alt="Screen Shot 2022-04-22 at 15 41 54" src="https://user-images.githubusercontent.com/508629/164783204-8da59add-5e52-4fa1-bc38-716c20c0037e.png">
looked at changing key as well but the interface there is broken as well

**Comment by joadr** [comment]
I'm able to reproduce the error, working on it!

**Comment by joadr** [comment]
While we fix this, you can use this endpoint which uses the previous version:

https://api2.orionx.io/graphql

notice that this endpoint uses .io domain instead of .com

I apologize for the issue! We are working in a patch

**Comment by lathanbritz** [comment]
No worries, tool still in development.

<img width="1255" alt="Screen Shot 2022-04-22 at 16 34 05" src="https://user-images.githubusercontent.com/508629/164789812-81281c2e-8204-48b1-a7e1-fdad1117e69a.png">
<img width="1321" alt="Screen Shot 2022-04-22 at 16 34 20" src="https://user-images.githubusercontent.com/508629/164789823-73197c67-0b64-42f8-b7f0-40053e938026.png">
same for the .com 

I'll switch to one of the other exchanges in the interum.

**Comment by lathanbritz** [comment]
Rocking that got me in! Thanks

**Comment by joadr** [comment]
The issue has been patched and is already in production, could you switch back to https://api2.orionx.com/graphql and try again, please?

**Comment by lathanbritz** [comment]
working for me on https://api2.orionx.com/graphql again
