### ISSUE TITLE
Pusher is broken

### ISSUE THREAD

**Issue by lathanbritz** [orionx-dev/orionx-sdk-js#36]
There are no results coming through pusher. 

test, use the websocket examples package. Set the config to your account then add some limit orders as an example. No data is pushed through the websockets. When pusher is working the function myOrders() will return the orders that are add/removed/updated.... 

Using that websocket examples package, we can also see that all the other websockets are also not returning data.

There needs to be away to validate that we are connected and receiving data from the websocket. 

1. Please add a ping / pong call back.
2. Please add a status page to orionx.com with the websockets status.

I have tried your other suggestion when the sdk broke of switching to 'https://api2.orionx.io/graphql' but that seems to do nothing.

**Comment by joadr** [comment]
Hello @lathanbritz! We found the issue and has already been fixed, please confirm if you still have issues!

**Comment by lathanbritz** [comment]
@jodar yup it working again, thanks.

**Comment by joadr** [comment]
@lathanbritz Great! 

About 1: we have used pusher for a long time and we are currently paying a lot for their service and we are not very happy with it. We are currently working on replacing it with our own websocket server, so we don't want to waste more resources on adding features to it

About 2: To be honest it has low prioritization on our backlog, as our quarter goals are very ambitious and it doesn't add too much value to the majority of our clients. I will move it up a bit tho, as it has been requested with the latest downtimes as we are switching our infrastructure.

PD: Jodar must be like 🤨 🤨 🤨 🤨  hahahahah
